import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import MySession from "@/components/MySession/MySession";

const exo = Exo({subsets:['latin'],variable:'--font-exo'});



export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full",  "font-sans",exo.variable)}
    >
      <body className="">
         <MySession >

        <Navbar />
        <Toaster />
        {children}
        <Footer />
         </MySession>
        </body>
    </html>
  );
}
